### ISSUE TITLE
Hide player control in full screen when video is paused

### ISSUE THREAD

**Issue by shukrifathil** [nralbrecht/youtube-hide-controls#22] opened 2023-01-11 01:05 UTC
This isn't really a bug but more of a feature request. 

Do you think you can add a feature to hide the player control entirely when the video is paused in full screen? It will still show up when you hover over the area (along with the Invert Trigger).

**Comment by nralbrecht** [comment] 2023-01-11 01:39
You should be able to hide the controls in full screen mode using the mouse trigger or the hotkey. Is that not enough for you?
Can you elaborate what behavior you want changed?

**Comment by shukrifathil** [comment] 2023-01-11 01:45
It seems like it might be a bug because it did work as intended normally but just recently the player control keeps showing. Maybe it's something to do on my setup.

**Comment by nralbrecht** [comment] 2023-01-11 02:02
I am sorry for that. Let me know if I can help you in any way. 
It would be great if you were able to find a way to reproduce your problem.

Some questions to narrow down the problem:
- Do you maybe use other add-ons that modify YouTube?
- Do you use Google Chrome or Mozilla Firefox.
- Do you have the latest version installed? (v3.1.4)

I have not had any problems since the last update.

**Comment by shukrifathil** [comment] 2023-01-11 02:07
- Yes, [Enhancer for YouTube](https://addons.mozilla.org/en-US/firefox/addon/enhancer-for-youtube/?utm_content=addons-manager-reviews-link&utm_medium=firefox-browser&utm_source=firefox-browser) and [Stylus](https://addons.mozilla.org/en-US/firefox/addon/styl-us/?utm_content=addons-manager-reviews-link&utm_medium=firefox-browser&utm_source=firefox-browser) to modify CSS
- Firefox
- Yes, v3.1.4

**Comment by nralbrecht** [comment] 2023-01-12 00:34
I tried around with _Enhancer for YouTube_. For me the controls are being hidden and are staying hidden reliably.

Are you using the Hotkey? Does your key binding collide with other add-ons like _Enhancer for YouTube_?

Otherwise I don't know how to help you until you find a way to reproduce the issue.

**Comment by shukrifathil** [comment] 2023-01-12 00:40
Yes, I'm aware that it's not the extension fault. I should just close this since it's not something I can reproduce and it's rare and random. I also have other extensions and  did a couple of modifications to the behaviour of Firefox as well, so who knows what's the cause.

**Comment by nralbrecht** [comment] 2023-01-12 00:42
Alright. I am closing this. Feel free to reopen if it turns out to be a problem with this add-on.

**Closed as completed by nralbrecht** 2023-01-12 00:42 UTC
