### ISSUE TITLE
"Could not unzip extension" error from Chrome Store

### ISSUE THREAD

**Issue by J-Reis** [nralbrecht/youtube-hide-controls#19] opened 2022-10-17 04:16 UTC
This may well be a web store problem and no fault of this extension's dev(s). Unfortunately it will probably fall to you to get it sorted regardless. Hopefully I'm helping out by making a note of it! If not, please forgive (and feel free to close this issue).
<details> 
  <summary>screenshot</summary>

![2022-10-16_23-08-16](https://user-images.githubusercontent.com/23666144/196087643-8a1c1bcd-0c01-4826-bdb2-a2e90046d268.png)
</details>

**Comment by nralbrecht** [comment] 2022-10-29 01:49
I can confirm that this happens in my chrome too. I will be investigating.

**Comment by nralbrecht** [comment] 2022-11-24 15:59
It looks like I finally got it to work. For some undocumented reason, Chrome is only able to read ZIPs that are created by 7zip. The Chrome Webstore just accepts them like it always has, but the browser is then not able to read it like it always has.

**Closed by nralbrecht** 2022-11-24 15:59 UTC
